In [4]:
import pandas as pd
path = "/home/furkan/projects/cpak/cpak-furkan-2026-04-13/labeled-data/video/CollectedData_furkan.h5"
h5 = pd.read_hdf(path)
h5.head()

scorer                             furkan                                      \
bodyparts                               1                       2
coords                                  x           y           x           y
labeled-data video 4000.l.png  367.785861  308.539572  324.133515  277.303893
                   4000.r.png  334.575993  295.706751  376.670151  261.026905
                   4001.l.png  306.768781  275.376376  264.277021  246.576406
                   4001.r.png  283.872499  282.175964  313.983259  241.710459
                   4002.l.png  393.104160  415.110027  361.772713  378.755981

scorer                                                                         \
bodyparts                               3                       4
coords                                  x           y           x           y
labeled-data video 4000.l.png  399.603570  301.167188  339.654349  250.530467
                   4000.r.png  306.832116  288.292439  355.862244  237.109770
                   4001.l.png  336.513013  263.100979  280.958972  218.878073
                   4001.r.png  247.727589  279.166158  294.625902  219.205564
                   4002.l.png  417.105148  409.541892  375.780928  353.860900

scorer                                                 ...              \
bodyparts                               5              ...          47
coords                                  x           y  ...           x
labeled-data video 4000.l.png  394.171278  252.082550  ...  400.313319
                   4000.r.png  302.287861  243.089053  ...  321.999072
                   4001.l.png  329.116299  219.350204  ...  398.616888
                   4001.r.png  245.366936  233.684238  ...  260.651742
                   4002.l.png  420.015305  357.159077  ...  390.974838

scorer                                                               \
bodyparts                                           48
coords                                   y           x            y
labeled-data video 4000.l.png  1424.489523  425.336244  1422.443623
                   4000.r.png  1423.550881  297.615900  1420.487027
                   4001.l.png  1338.751624  423.325059  1334.030317
                   4001.r.png  1332.993276  234.481322  1328.269834
                   4002.l.png  1439.780979  412.294156  1438.759694

scorer                                                              \
bodyparts                              49                       50
coords                                  x            y           x
labeled-data video 4000.l.png  417.939530  1424.804276  383.496317
                   4000.r.png  304.509572  1423.678541  337.318342
                   4001.l.png  416.557853  1337.335232  385.082475
                   4001.r.png  241.885636  1331.461349  275.843351
                   4002.l.png  405.911127  1439.270336  376.804514

scorer
bodyparts                                           51
coords                                   y           x            y
labeled-data video 4000.l.png  1434.515893  433.909659  1429.286614
                   4000.r.png  1433.891388  287.403054  1429.678589
                   4001.l.png  1351.341775  434.341441  1343.787684
                   4001.r.png  1346.397637  225.034439  1342.823141
                   4002.l.png  1449.227862  418.677185  1448.844880

[5 rows x 102 columns]

In [5]:
csv_path = "/home/furkan/projects/cpak/cpak-furkan-2026-04-13/labeled-data/video/CollectedData_furkan.csv"
csv = pd.read_csv(csv_path)
csv.head()

,scorer,Unnamed: 1,Unnamed: 2,furkan,furkan.1,furkan.2,furkan.3,furkan.4,furkan.5,furkan.6,...,furkan.92,furkan.93,furkan.94,furkan.95,furkan.96,furkan.97,furkan.98,furkan.99,furkan.100,furkan.101
0,bodyparts,NaN,NaN,1,1,2,2,3,3,4,...,47,47,48,48,49,49,50,50,51,51
1,coords,NaN,NaN,x,y,x,y,x,y,x,...,x,y,x,y,x,y,x,y,x,y
2,labeled-data,video,4000.l.png,367.7858605792452,308.5395718813882,324.13351501334796,277.30389349867954,399.6035702361658,301.1671875828266,339.65434899233367,...,400.3133189505636,1424.4895226632934,425.3362441069554,1422.4436231222048,417.93953038148106,1424.8042764388454,383.4963172470647,1434.5158930358764,433.9096592446421,1429.2866143738308
3,labeled-data,video,4000.r.png,334.5759932703861,295.70675087199413,376.67015129770414,261.0269047699423,306.8321163887446,288.2924389467279,355.86224363647307,...,321.99907168203487,1423.5508806206835,297.6159004979498,1420.4870266499086,304.50957193219375,1423.6785412027991,337.3183415359103,1433.8913877720495,287.4030539286995,1429.6785885622337
4,labeled-data,video,4001.l.png,306.7687811799589,275.3763761318664,264.2770214804257,246.57640566884942,336.5130129696322,263.10097888533454,280.9589715846869,...,398.6168875449162,1338.7516239149606,423.3250589257559,1334.0303172816791,416.5578527513858,1337.3352319249761,385.082475196176,1351.3417749370444,434.3414410700793,1343.787684323794